apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:64847
  name: docker-desktop

users:
- name: docker-desktop
  user:
    client-certificate-data: ...
    client-key-data: ...
     
contexts:
- context:
    name: docker-desktop
    cluster: docker-desktop
    user: docker-desktop

current-context: docker-desktop